import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    marginTop: 80,
    alignItems: "center",
  },
  title: {
    fontSize: 30,
    color: "#FFF",
    fontWeight: "bold",
    marginBottom: 20,
  },
  pedidosBox: {
    backgroundColor: "#FFFFFFEE",
    borderRadius: 20,
    padding: 15,
    width: "90%",
    height: "55%",
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  pedidoItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 15,
    marginBottom: 12,
    padding: 10,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  pedidoImagem: {
    width: 45,
    height: 45,
    borderRadius: 10,
    marginRight: 10,
  },
  pedidoInfo: {
    flex: 1,
  },
  pedidoNome: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#333",
  },
  pedidoPreco: {
    color: "#555",
    fontSize: 15,
  },
  pedidoQuantidade: {
    color: "#00A650",
    fontWeight: "bold",
  },
  cancelarBtn: {
    backgroundColor: "#E53935",
    borderRadius: 50,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  cancelarBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  subtotalBox: {
    backgroundColor: "#FFF",
    borderRadius: 12,
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  subtotalLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#444",
  },
  subtotalValor: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111",
  },
  cardapioBtn: {
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 80,
    marginBottom: 15,
  },
  cardapioBtnText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  pagamentoBtn: {
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 80,
    marginBottom: 15,
  },
  pagamentoBtnText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  fecharMesaBtn: {
    backgroundColor: "#E53935",
    borderRadius: 15,
    paddingVertical: 15,
    width: "80%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  fecharMesaBtnText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
});
